#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "Usage: submit-qchem <input file> <walltime (in hrs)>"
    exit 1
fi

JOBNAME=${1/.in/}
TIME=$2

cat <<EOF > $PWD/run-qchem.pbs
#!/bin/bash

#PBS -N ${JOBNAME}
#PBS -q shared
#PBS -l nodes=1:ppn=1
#PBS -l walltime=${TIME}:00:00
#PBS -j oe
#PBS -l qos=low
#PBS -m abe
#PBS -M ${USER}@pitt.edu

module load qchem/dlambrecht/4.1-release.O2.serial

cp \$PBS_O_WORKDIR/${JOBNAME}.qcin \$LOCAL
cd \$LOCAL

run_on_exit() {
    set -v
    cp -r \$LOCAL/* \$PBS_O_WORKDIR
}

trap run_on_exit EXIT

qchem -save ${JOBNAME}.qcin \$PBS_O_WORKDIR/${JOBNAME}.out

EOF

# qsub $PWD/run-qchem.pbs
