#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: submit-qchem <input file> <ppn> <walltime (in hrs)>"
    exit 1
fi

JOBNAME=${1/.in/}
PPN=$2
TIME=$3

cat <<EOF > $PWD/run-qchem.pbs
#!/bin/bash

#PBS -N ${JOBNAME}
#PBS -q shared
#PBS -l nodes=1:ppn=${PPN}
#PBS -l walltime=${TIME}:00:00
#PBS -j oe
#PBS -l qos=low
#PBS -m abe
#PBS -M ${USER}@pitt.edu

module load qchem/dlambrecht/4.1-trunk.20130919.ompO0

cp \$PBS_O_WORKDIR/${JOBNAME}.qcin \$LOCAL
cd \$LOCAL

run_on_exit() {
    set -v
    cp -r \$LOCAL/* \$PBS_O_WORKDIR
}

trap run_on_exit EXIT

qchem -save -nt ${PPN} ${JOBNAME}.qcin \$PBS_O_WORKDIR/${JOBNAME}.out

EOF

qsub $PWD/run-qchem.pbs
